### ISSUE TITLE
Regarding upload item

### ISSUE THREAD

**Issue by Yenrenkhor** [JacobYim/CSE442-BuyNSell#116]
upload branch has been committed, but there is issue.

--main issue--

1. The page should be a .ejs file, not a .html, so that should be changed.
2. item_upload form is not connected to dashboard

-- minor issue --
Users might not need to insert product category since it would be done with image recognition in sprint 3.

**Comment by sangwookim96** [comment]
main issue 2. item_upload form is not connected to dashboard
Now solved.

**Comment by sangwookim96** [comment]
Check uploadfor_update branch

**Comment by sangwookim96** [comment]
Problem solved.
Check the Develop-Sprint-2 branch.
