### ISSUE TITLE
login_acceptance_test, and signin not working

### ISSUE THREAD

**Issue by hard2code** [JacobYim/CSE442-BuyNSell#142]
Acceptance test file for the feature listed below :
login
singin
add item
show item in category
add user image
change user image and information
change password
user-session
logout

1- sprint2-test.py
2- login_acceptance_test.py
3- signin_acceptance_test.py

To produce:
I followed the README file and run the server and database then I typed in the command line 
pyhton3 login_acceptance_test.py.

Issue:
running test file 1 pass successfully, but when I run the other two they gave me Cannot GET /signup.html
and Cannot GET /login.html

To fix:
I removed the two test files because I have been told by the dev team that the files are  for sprint 1.

**Comment by hard2code** [comment]
and also can you guys be more clear on how to install the chromedriver. because I had to change the directory inside your python test file to reflect usr/bin/chromedriver in my case insted of just ./chromedriver

**Comment by ChoongLiang** [comment]
Sorry about the confusion, actually both these files are for sprint 1 testing. So sprint2-test itself is fine.

**Comment by hard2code** [comment]
OK cool, I have created a pull request and I just removed the two files to avoid confusion when testing.
