### ISSUE TITLE
As a user I'd like to create a user account

### ISSUE THREAD

**Issue by ltanedo** [JacobYim/CSE442-BuyNSell#29]
As a user, I would like to sign up for this buy and sell website.

**Comment by ltanedo** [comment]
Acceptance Test (steps)
1. User clicks login field on the navbar
2. User can input (name, id, ,password, email, age) into text boxes
3. User can press submit to send details for account creation
 -> console will log(user's input fields
4. User will be redirected to success page

**Comment by JacobYim** [comment]
It has been implemented at #43
