### ISSUE TITLE
Signup form inputs saved as js variables

### ISSUE THREAD

**Issue by ltanedo** [JacobYim/CSE442-BuyNSell#31]
When user submits sign up form, field inputs translated to javascript code.  
- NPM Body Parser will be used to listen for inputs

**Comment by ChoongLiang** [comment]
(All for express)
Here is a good framework for that: 

http://www.passportjs.org/

Oh ya, btw, the message flashing we discussed earlier :
(ie, Register success! You can now login, ... redirect to Login Page)
Below is a good middleware to use.

https://github.com/jaredhanson/connect-flash

**Comment by ltanedo** [comment]
That passportjs thing is cool once we link the sign up with services like google or facebook (from what I've read).

For the successes message, i was thinking of just loading another html page.  Did that with my website lol. Anyways for  now it just goes back to login.

**Comment by JacobYim** [comment]
#38 

In the `login` branch, the NPM Body Parser has been used.
