### ISSUE TITLE
Password Hashing for Security

### ISSUE THREAD

**Issue by ltanedo** [JacobYim/CSE442-BuyNSell#32]
Password Hashing will be used to protect user's password from database/server attack.
- NPM password-hash will be implemented

**Comment by ChoongLiang** [comment]
Same.. Here is a good framework for that: 

https://www.npmjs.com/package/bcryptjs

**Comment by ltanedo** [comment]
Yeah used password-hash but its recently been dissaproved.  Gotta switch to bcryptjs.

**Comment by JacobYim** [comment]
We adopted the 'password-hash' module recommended by @ltanedo  @ChoongLiang 

It applied and fixed minor issues #55 #56 #57 at merge request at #58
