### ISSUE TITLE
As a user, I want navigation for all pages working

### ISSUE THREAD

**Issue by ChoongLiang** [JacobYim/CSE442-BuyNSell#82]
- Add on necessary pages such as: sell product, user panel, search, category, about and contact page.

**Comment by JacobYim** [comment]
About the products or Item
- Registering Product page
- Displaying an item page (With comments part of buyers)
- Dashboard of items (List of the items)

About the users
- User profile panel
- reset password page
- logout slot
- remove account page

**Comment by JacobYim** [comment]
This is updated at the #98 merge request.
