### ISSUE TITLE
All my information showed up in the link when I register and login

### ISSUE THREAD

**Issue by ChoongLiang** [JacobYim/CSE442-BuyNSell#9]
the issue might be in the html, we have to post or get from the database.

**Comment by ChoongLiang** [comment]
We can solve this by redirecting the page to a specified user dashboard

**Comment by sangwookim96** [comment]
Which information should be visible to users? (e.g. ID, P/W, exchange history, etc.)

**Comment by JacobYim** [comment]
It has been solved by changing the method to post.

**Comment by JacobYim** [comment]
It has been continue to #44
