### ISSUE TITLE
Need JavaScript function that read JSON data of a product.

### ISSUE THREAD

**Issue by sangwookim96** [JacobYim/CSE442-BuyNSell#91]
The product JSON data must have:
  - Product Name
  - Price
  - Image src
  - Seller information

**Comment by sangwookim96** [comment]
Our project is now using ejs. Therefore, there is no need to use JSON to update page.

**Comment by JacobYim** [comment]
#87 #123 This is reflected at the #97 merge request. The using ejs implement the user login session.
