### ISSUE TITLE
Dashboard page's contents are now adjustable by JSON

### ISSUE THREAD

**Issue by sangwookim96** [JacobYim/CSE442-BuyNSell#93]
Since JS obtain the necessary JSON data, JS can show the products information to the user needs.

Before: 
  The page is static (doesn't change contents).

Now:
  The page can show the various data from the JSON data which JS obtained.

**Comment by JacobYim** [comment]
this issue is continue with the issue #94.

**Comment by JacobYim** [comment]
this issue is resolved by the merge request #97
